---
title: "DailyMinimum"
author: "Kathleen Mason"
date: "1/28/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(ggridges)
library(dplyr)

getwd()

mytheme <- theme_light(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

Upstream1_AllDO<-read_csv("./Processed/MilburnieDam_Upstream1_AllDO_processed.csv")
Upstream2_AllDO<-read_csv("./Processed/MilburnieDam_Upstream2_AllDO_processed.csv")
Impoundment1_AllDO<-read_csv("./Processed/MilburnieDam_Impoundment1_AllDO_processed.csv")
Downstream1_AllDO<-read_csv("./Processed/MilburnieDam_Downstream1_AllDO_processed.csv")
Downstream2A_AllDO<-read_csv("./Processed/MilburnieDam_Downstream2A_AllDO_processed.csv")
Downstream2B_AllDO<-read_csv("./Processed/MilburnieDam_Downstream2B_AllDO_processed.csv")


#Now take the minimum of each day!
```

```{r Take the daily minimum}




Upstream1_MinDO<-  
  Upstream1_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(`Dissolved Oxygen`))

Upstream2_MinDO<-  
  Upstream2_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(`Dissolved Oxygen`))

Impoundment1_MinDO<-  
  Impoundment1_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(`Dissolved Oxygen`))

Downstream1_MinDO<-  
  Downstream1_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(`Dissolved Oxygen`))

Downstream2A_MinDO<-  
  Downstream2A_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(`Dissolved Oxygen`))

Downstream2B_MinDO<-  
  Downstream2B_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(`Dissolved Oxygen`))

#Combine all Min's together into one dataset
#First give them all another column identifying their site location
Upstream1_MinDO$Location<-"Upstream1"
Upstream2_MinDO$Location<-"Upstream2"
Impoundment1_MinDO$Location<-"Impoundment1"
Downstream1_MinDO$Location<-"Downstream1"
Downstream2A_MinDO$Location<-"Downstream2A"
Downstream2B_MinDO$Location<-"Downstream2B"
#Now Combine into one dataset (later potentially will graph as one dataset)
All1<-rbind(Upstream1_MinDO, Upstream2_MinDO)
All2<-rbind(All1, Impoundment1_MinDO)
All3<-rbind(All2, Downstream1_MinDO)
All4<-rbind(All3, Downstream2A_MinDO)
AllMinDO<-rbind(All4, Downstream2B_MinDO)

#Combine only representative sites
Rep1<-rbind(Upstream2_MinDO, Impoundment1_MinDO)
RepSites_MinDO<-rbind(Rep1, Downstream2B_MinDO)
#Save these

write.csv(AllMinDO, row.names = FALSE, file =("./Processed/MilburnieDam_UAllMinDO_processed.csv"))
write.csv(RepSites_MinDO, row.names = FALSE, file =("./Processed/MilburnieDam_RepSites_MinDO_processed.csv"))


#Need the difference between upstream and impoundment- I have one impoundment site but which upstream do I use?
#I guess I'll try it with both- first I need to combine the impoudment and upstream datasets, probably so the columns of MinDO for Upstream is next to the Impoundment MinDO...then find the difference in a new column
```


```{r Combining Upstream and Impoundment}
colnames(Upstream2_MinDO)[2] <- "Upstream2_MinDO"
colnames(Impoundment1_MinDO)[2] <- "Impoundment1_MinDO"

Up2andImp_MinDO<-cbind(Upstream2_MinDO, Impoundment1_MinDO)
Up2andImp_MinDO <- left_join(Upstream2_MinDO,Impoundment1_MinDO,by="Date")

#Now find difference between the two, but will the NA's affect this?

```

```{r Compute Difference}


Up2andImp1_MinDO_Diff<-Up2andImp_MinDO%>%
  mutate(Diff= Impoundment1_MinDO-Upstream2_MinDO)

#Save this dataset
write.csv(Up2andImp1_MinDO_Diff, row.names = FALSE, file =("./Processed/MilburnieDam_Up2andImp1_MinDO_Diff_processed.csv"))
```

```{r Separate all MinDO and Diff data into before and after removal }
Up2andImp1_MinDO_Diff_Before <- Up2andImp1_MinDO_Diff %>% filter(Date < as.Date("2017-09-21"))

Up2andImp1_MinDO_Diff_After <- Up2andImp1_MinDO_Diff %>% filter(Date > as.Date("2017-09-21"))


Up2andImp1_MinDO_Diff_After$TimeStamp<-"After"
Up2andImp1_MinDO_Diff_Before$TimeStamp<-"Before"

#Save these
write.csv(Up2andImp1_MinDO_Diff_After, row.names = FALSE, file =("./Processed/MilburnieDam_Up2andImp1_MinDO_Diff_After_processed.csv"))
write.csv(Up2andImp1_MinDO_Diff_Before, row.names = FALSE, file =("./Processed/MilburnieDam_Up2andImp1_MinDO_Diff_Before_processed.csv"))

#AllMinDO
AllMinDO_Before <- AllMinDO %>% filter(Date < as.Date("2017-09-21"))

AllMinDO_After <- AllMinDO %>% filter(Date > as.Date("2017-09-21"))


AllMinDO_After$TimeStamp<-"After"
AllMinDO_Before$TimeStamp<-"Before"

write.csv(AllMinDO_After, row.names = FALSE, file =("./Processed/MilburnieDam_AllMinDO_After_processed.csv"))
write.csv(AllMinDO_Before, row.names = FALSE, file =("./Processed/MilburnieDam_AllMinDO_Before_processed.csv"))

```

```{r Graph AllMinDO}

#creating line of dam removal date
d=data.frame(date=as.Date(c("2017-09-21")), event=c("Dam Removal"))

Before_MinDOplot <-ggplot(AllMinDO_Before, aes(x = Date, y = MinDO)) +
geom_line(size=.75, color="royalblue4")  + ylim(0, 15) +ylab("Daily Minimum DO (mg/L)")+ xlab("Sampling Date")+scale_x_date(date_breaks = "1 year", date_minor_breaks= "months", date_labels = "%m/%y")+
  labs(title = "Avg Minimum DO Before Removal")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25))+   
    geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)

Before_MinDOplot
ggsave("./Outputs/Before_MinDOplot.jpg", plot=Before_MinDOplot, width =10, height=6, units="in", dpi=300)


After_MinDOplot <-ggplot(AllMinDO_After, aes(x = Date, y = MinDO)) +
geom_line(size=.75, color="royalblue4")  + ylim(0, 15) +ylab("Daily Minimum DO (mg/L)")+ xlab("Sampling Date")+scale_x_date(date_breaks = "1 year", date_minor_breaks= "months", date_labels = "%m/%y")+
  labs(title = "Avg Minimum DO After Removal")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25))+   
    geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)

After_MinDOplot
ggsave("./Outputs/After_MinDOplot.jpg", plot=After_MinDOplot, width =10, height=6, units="in", dpi=300)

```

```{r Graph DODiff}
MinDODiff_Before_plot <-ggplot(Up2andImp1_MinDO_Diff_Before, aes(x = Date, y = Diff)) +
geom_line(size=.75, color="royalblue4")   +ylab("")+ xlab("Sampling Date")+scale_x_date(date_breaks = "3 month", date_minor_breaks= "months", date_labels = "%m/%y", limits = as.Date(c('2013-10-11','2015-07-01')))+
  labs(title = "Before")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), aspect.ratio = 5/30, plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12))
#+   
   # geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)

MinDODiff_Before_plot
ggsave("./Outputs/MinDODiff_Before_plot.jpg", plot=MinDODiff_Before_plot, width =10, height=6, units="in", dpi=300)

MinDODiff_After_plot <-ggplot(Up2andImp1_MinDO_Diff_After, aes(x = Date, y = Diff)) +
geom_line(size=.75, color="royalblue4")   +ylab("")+ xlab("Sampling Date")+scale_x_date(date_breaks = "3 month", date_minor_breaks= "months", date_labels = "%m/%y", limits = as.Date(c('2017-09-22','2019-07-10')))+
  labs(title = "After")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), aspect.ratio = 5/30, plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12))

MinDODiff_After_plot
ggsave("./Outputs/MinDODiff_After_plot.jpg", plot=MinDODiff_After_plot, width =10, height=6, units="in", dpi=300)

#Combine
MinDO_Diff_RepresentativeSites_CombinedPlot<-plot_grid(MinDODiff_Before_plot,MinDODiff_After_plot, 
         #labels = c("Upstream 2", "Impoundment 1", "Downstream 2B" ),
         ncol = 2, nrow = 1)
MinDO_Diff_RepresentativeSites_CombinedPlot
ggsave("./Outputs/MilburnieDam_MinDO_Diff_RepresentativeSites_CombinedPlot.jpg", plot=MinDO_Diff_RepresentativeSites_CombinedPlot, width =10, height=6, units="in", dpi=300)


```

#Next Steps:
#Combine Up2, Imp1, Down2b into one dataset, graph daily min over time --Check, done in chunk 2
  #Bound date so no major time gaps
  #Divide into before and after
#Make difference of up2 and Imp1 dataset
#Graph this over time
  #divide into before and after
  #Rid of major time gaps
```{r RepSites_MinDO}
RepSites_MinDO_Before <- RepSites_MinDO %>% filter(Date < as.Date("2017-09-21"))

RepSites_MinDO_After <- RepSites_MinDO %>% filter(Date > as.Date("2017-09-21"))


RepSites_MinDO_After$TimeStamp<-"After"
RepSites_MinDO_Before$TimeStamp<-"Before"

#Let's try graphing
#Before
RepSites_MinDO_Before_plot <-ggplot(RepSites_MinDO_Before, aes(x = Date, y = MinDO)) +
geom_line(size=.75, color="royalblue4")  + ylim(0, 15) +ylab("Daily Minimum DO (mg/L)")+ xlab("Sampling Date")+ scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2013-10-11','2015-07-01')))+
  labs(title = "Before")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), aspect.ratio=4/16) #+   
    #geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)
RepSites_MinDO_Before_plot
ggsave("./Outputs/RepSites_MinDO_Before_plot.jpg", plot=RepSites_MinDO_Before_plot, width =10, height=6, units="in", dpi=300)

#After
RepSites_MinDO_After_plot <-ggplot(RepSites_MinDO_After, aes(x = Date, y = MinDO)) +
geom_line(size=.75, color="royalblue4")  + ylim(0, 15) +ylab("Daily Minimum DO (mg/L)")+ xlab("Sampling Date")+ scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2017-09-22','2019-07-10')))+
  labs(title = "After")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), aspect.ratio=4/16) #+   
    #geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)
RepSites_MinDO_After_plot
ggsave("./Outputs/RepSites_MinDO_After_plot.jpg", plot=RepSites_MinDO_After_plot, width =10, height=6, units="in", dpi=300)


#It is still plotting a line where dates are not actually recorded for having any data-- HOW DO I MAKE AN OBVIOUS GAP IN DATA GRAPHED???
#Used aspect ratio to widen out the data- ultimately alters slopes of lines between sampling dates

```

```{r Attempt 2}

RepSites_MinDO_Before_plot2 <-ggplot(RepSites_MinDO_Before, aes(x = Date, y = MinDO, color=Location)) +
geom_point(size=.75) + ylim(0, 15)+ ylab("")+
 xlab("")+
  labs(title = "Before")+
  scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2013-10-11','2015-07-01')))+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12), legend.position = "bottom", legend.title = element_blank(), aspect.ratio=5/30, legend.text=element_text(size=10))
RepSites_MinDO_Before_plot2
ggsave("./Outputs/MilburnieDam_RepSites_MinDO_Before_plot2.jpg", plot=RepSites_MinDO_Before_plot2, width =10, height=6, units="in", dpi=300)

RepSites_MinDO_After_plot2 <-ggplot(RepSites_MinDO_After, aes(x = Date, y = MinDO, color=Location)) +
geom_point(size=.75) + ylim(0, 15)+ ylab("")+
 xlab("")+
  labs(title = "After")+
  scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2017-09-22','2019-07-10')))+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12), aspect.ratio=5/30)
RepSites_MinDO_After_plot2
ggsave("./Outputs/MilburnieDam_RepSites_MinDO_After_plot2.jpg", plot=RepSites_MinDO_After_plot2, width =10, height=6, units="in", dpi=300)


#install.packages("gridGraphics")
library(gridGraphics)
library(cowplot)
legend_MinDO<-get_legend(RepSites_MinDO_After_plot2+ theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank(), legend.text = element_text( size = 10)))
legend_MinDO
#Combine
MinDO_RepresentativeSites_CombinedPlot<-plot_grid(RepSites_MinDO_Before_plot2+theme(legend.position="none"),RepSites_MinDO_After_plot2+ theme(legend.position="none"), 
         #labels = c("Upstream 2", "Impoundment 1", "Downstream 2B" ),
         ncol = 2, nrow = 1)
MinDO_RepresentativeSites_CombinedPlot
ggsave("./Outputs/MilburnieDam_MinDO_RepresentativeSites_CombinedPlot.jpg", plot=MinDO_RepresentativeSites_CombinedPlot, width =10, height=6, units="in", dpi=300)

Final_MinDO_Combined<-plot_grid(MinDO_RepresentativeSites_CombinedPlot, legend_MinDO, ncol=1)
Final_MinDO_Combined
```

```{r Final combining}
#combine min Diff graph of before and after with minDO rep sites before and after

Final_MinDO_DiffDO<-plot_grid(MinDO_Diff_RepresentativeSites_CombinedPlot,Final_MinDO_Combined, 
         labels = c("A", "B" ),
         ncol = 1, nrow = 2)
Final_MinDO_DiffDO
ggsave("./Outputs/MilburnieDam_Final_MinDO_DiffDO.jpg", plot=Final_MinDO_DiffDO, width =10, height=6, units="in", dpi=300)



```

