---
title: "DOThresholds"
author: "Kathleen Mason"
date: "10/22/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Setup}
library(tidyverse)
library(ggridges)
library(dplyr)


getwd()


Upstream1_AllDO<-read.csv("./Processed/MilburnieDam_Upstream1_AllDO_processed.csv")
Upstream2_AllDO<- read.csv("./Processed/MilburnieDam_Upstream2_AllDO_processed.csv")
Impoundment1_AllDO<-read.csv("./Processed/MilburnieDam_Impoundment1_AllDO_processed.csv")
Downstream1_AllDO<-read.csv("./Processed/MilburnieDam_Downstream1_AllDO_processed.csv")
Downstream2A_AllDO<-read.csv("./Processed/MilburnieDam_Downstream2A_AllDO_processed.csv")
Downstream2B_AllDO<-read.csv("./Processed/MilburnieDam_Downstream2B_AllDO_processed.csv")

class(Upstream1_AllDO$Dissolved.Oxygen)

```

```{r}
#newdata <- mydata[ which(mydata$gender=='F' 
#& mydata$age > 65), ]

Upstream1_Threshold4<- Upstream1_AllDO[which(Upstream1_AllDO$Dissolved.Oxygen <= 4),]
Upstream1_Threshold6<- Upstream1_AllDO[which(Upstream1_AllDO$Dissolved.Oxygen <= 6),]
#92603 observations
#Threshold 4: 5468
#Threshold 6: 11136

Upstream2_AllDO1_Threshold4<- Upstream2_AllDO[which(Upstream2_AllDO$Dissolved.Oxygen <= 4),]
Upstream2_AllDO1_Threshold6<- Upstream2_AllDO[which(Upstream2_AllDO$Dissolved.Oxygen <= 6),]
#97430 observations
#Threshold 4: 1289
#Threshold 6: 9803

Impoundment1_AllDO1_Threshold4<- Impoundment1_AllDO[which(Impoundment1_AllDO$Dissolved.Oxygen <= 4),]
Impoundment1_AllDO1_Threshold6<- Impoundment1_AllDO[which(Impoundment1_AllDO$Dissolved.Oxygen <= 6),]
#92823 observations
#Threshold 4: 5388
#Threshold 6: 14653

Downstream1_Threshold4<- Downstream1_AllDO[which(Downstream1_AllDO$Dissolved.Oxygen <= 4),]
Downstream1_Threshold6<- Downstream1_AllDO[which(Downstream1_AllDO$Dissolved.Oxygen <= 6),]
#86807 observations
#Threshold 4: 3027
#Threshold 6: 5264

Downstream2A_Threshold4<- Downstream2A_AllDO[which(Downstream2A_AllDO$Dissolved.Oxygen <= 4),]
Downstream2A_Threshold6<- Downstream2A_AllDO[which(Downstream2A_AllDO$Dissolved.Oxygen <= 6),]
#78363 observations
#Threshold 4: 2153
#Threshold 6: 12744

Downstream2B_Threshold4<- Downstream2B_AllDO[which(Downstream2B_AllDO$Dissolved.Oxygen <= 4),]
Downstream2B_Threshold6<- Downstream2B_AllDO[which(Downstream2B_AllDO$Dissolved.Oxygen <= 6),]
#96055 observations
#Threshold 4: 3259
#Threshold 6: 10548
```

```{r Save Threshold Datasets}
write.csv(Upstream1_Threshold4, row.names = FALSE, file =("./Processed/MilburnieDam_Upstream1_Threshold4_processed.csv"))
write.csv(Upstream1_Threshold6, row.names = FALSE, file =("./Processed/MilburnieDam_Upstream1_Threshold6_processed.csv"))

write.csv(Upstream2_Threshold4, row.names = FALSE, file =("./Processed/MilburnieDam_Upstream2_Threshold4_processed.csv"))
write.csv(Upstream2_Threshold6, row.names = FALSE, file =("./Processed/MilburnieDam_Upstream2_Threshold6_processed.csv"))

write.csv(Impoundment1_Threshold4, row.names = FALSE, file =("./Processed/MilburnieDam_Impoundment1_Threshold4_processed.csv"))
write.csv(Impoundment1_Threshold6, row.names = FALSE, file =("./Processed/MilburnieDam_Impoundment1_Threshold6_processed.csv"))

write.csv(Downstream1_Threshold4, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream1_Threshold4_processed.csv"))
write.csv(Downstream1_Threshold6, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream1_Threshold6_processed.csv"))

write.csv(Downstream2A_Threshold4, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream2A_Threshold4_processed.csv"))
write.csv(Downstream2A_Threshold6, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream2A_Threshold6_processed.csv"))

write.csv(Downstream2B_Threshold4, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream2B_Threshold4_processed.csv"))
write.csv(Downstream2B_Threshold6, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream2B_Threshold6_processed.csv"))
```

```{r Before vs After Dam Removal Comparison of Thresholds}
#newdata <- mydata[ which(mydata$gender=='F' 
#& mydata$age > 65), ]

Upstream1_Before.All<- Upstream1_AllDO[which(Upstream1_AllDO$TimeStamp=='Before') ,]
#45812
Upstream1_After.All<- Upstream1_AllDO[which(Upstream1_AllDO$TimeStamp=='After') ,]
#37425

Upstream1_Before.Threshold4<- Upstream1_AllDO[which(Upstream1_AllDO$TimeStamp=='Before' & Upstream1_AllDO$Dissolved.Oxygen <= 4),]
Upstream1_After.Threshold4<- Upstream1_AllDO[which(Upstream1_AllDO$TimeStamp=='After' & Upstream1_AllDO$Dissolved.Oxygen <= 4),]
#Before: 192
#After: 5276

Upstream1_Before.Threshold6<- Upstream1_AllDO[which(Upstream1_AllDO$TimeStamp=='Before' & Upstream1_AllDO$Dissolved.Oxygen <= 6),]
Upstream1_After.Threshold6<- Upstream1_AllDO[which(Upstream1_AllDO$TimeStamp=='After' & Upstream1_AllDO$Dissolved.Oxygen <= 6),]
#Before: 3160
#After: 7976



Upstream2_Before.All<- Upstream2_AllDO[which(Upstream2_AllDO$TimeStamp=='Before') ,]
#47843
Upstream2_After.All<- Upstream2_AllDO[which(Upstream2_AllDO$TimeStamp=='After') ,]
#37423

Upstream2_Before.Threshold4<- Upstream2_AllDO[which(Upstream2_AllDO$TimeStamp=='Before' & Upstream2_AllDO$Dissolved.Oxygen <= 4),]
Upstream2_After.Threshold4<- Upstream2_AllDO[which(Upstream2_AllDO$TimeStamp=='After' & Upstream2_AllDO$Dissolved.Oxygen <= 4),]
#Before: 513
#After: 776

Upstream2_Before.Threshold6<- Upstream2_AllDO[which(Upstream2_AllDO$TimeStamp=='Before' & Upstream2_AllDO$Dissolved.Oxygen <= 6),]
Upstream2_After.Threshold6<- Upstream2_AllDO[which(Upstream2_AllDO$TimeStamp=='After' & Upstream2_AllDO$Dissolved.Oxygen <= 6),]
#Before: 2619
#After: 7184



Impoundment1_Before.All<- Impoundment1_AllDO[which(Impoundment1_AllDO$TimeStamp=='Before') ,]
#39001
Impoundment1_After.All<- Impoundment1_AllDO[which(Impoundment1_AllDO$TimeStamp=='After') ,]
#36625

Impoundment1_Before.Threshold4<- Impoundment1_AllDO[which(Impoundment1_AllDO$TimeStamp=='Before' & Impoundment1_AllDO$Dissolved.Oxygen <= 4),]
Impoundment1_After.Threshold4<- Impoundment1_AllDO[which(Impoundment1_AllDO$TimeStamp=='After' & Impoundment1_AllDO$Dissolved.Oxygen <= 4),]
#Before: 2492
#After: 2896

Impoundment1_Before.Threshold6<- Impoundment1_AllDO[which(Impoundment1_AllDO$TimeStamp=='Before' & Impoundment1_AllDO$Dissolved.Oxygen <= 6),]
Impoundment1_After.Threshold6<- Impoundment1_AllDO[which(Impoundment1_AllDO$TimeStamp=='After' & Impoundment1_AllDO$Dissolved.Oxygen <= 6),]
#Before: 7094
#After: 7559



Downstream1_Before.All<- Downstream1_AllDO[which(Downstream1_AllDO$TimeStamp=='Before') ,]
#46809
Downstream1_After.All<- Downstream1_AllDO[which(Downstream1_AllDO$TimeStamp=='After') ,]
#25215

Downstream1_Before.Threshold4<- Downstream1_AllDO[which(Downstream1_AllDO$TimeStamp=='Before' & Downstream1_AllDO$Dissolved.Oxygen <= 4),]
Downstream1_After.Threshold4<- Downstream1_AllDO[which(Downstream1_AllDO$TimeStamp=='After' & Downstream1_AllDO$Dissolved.Oxygen <= 4),]
#Before: 1292
#After: 1735

Downstream1_Before.Threshold6<- Downstream1_AllDO[which(Downstream1_AllDO$TimeStamp=='Before' & Downstream1_AllDO$Dissolved.Oxygen <= 6),]
Downstream1_After.Threshold6<- Downstream1_AllDO[which(Downstream1_AllDO$TimeStamp=='After' & Downstream1_AllDO$Dissolved.Oxygen <= 6),]
#Before: 2227
#After: 3037



Downstream2A_Before.All<- Downstream2A_AllDO[which(Downstream2A_AllDO$TimeStamp=='Before') ,]
#32519
Downstream2A_After.All<- Downstream2A_AllDO[which(Downstream2A_AllDO$TimeStamp=='After') ,]
#33460

Downstream2A_Before.Threshold4<- Downstream2A_AllDO[which(Downstream2A_AllDO$TimeStamp=='Before' & Downstream2A_AllDO$Dissolved.Oxygen <= 4),]
Downstream2A_After.Threshold4<- Downstream2A_AllDO[which(Downstream2A_AllDO$TimeStamp=='After' & Downstream2A_AllDO$Dissolved.Oxygen <= 4),]
#Before: 0
#After: 2153

Downstream2A_Before.Threshold6<- Downstream2A_AllDO[which(Downstream2A_AllDO$TimeStamp=='Before' & Downstream2A_AllDO$Dissolved.Oxygen <= 6),]
Downstream2A_After.Threshold6<- Downstream2A_AllDO[which(Downstream2A_AllDO$TimeStamp=='After' & Downstream2A_AllDO$Dissolved.Oxygen <= 6),]
#Before: 1367
#After: 11377



Downstream2B_Before.All<- Downstream2B_AllDO[which(Downstream2B_AllDO$TimeStamp=='Before') ,]
#50233
Downstream2B_After.All<- Downstream2B_AllDO[which(Downstream2B_AllDO$TimeStamp=='After') ,]
#34018

Downstream2B_Before.Threshold4<- Downstream2B_AllDO[which(Downstream2B_AllDO$TimeStamp=='Before' & Downstream2B_AllDO$Dissolved.Oxygen <= 4),]
Downstream2B_After.Threshold4<- Downstream2B_AllDO[which(Downstream2B_AllDO$TimeStamp=='After' & Downstream2B_AllDO$Dissolved.Oxygen <= 4),]
#Before:291
#After: 2968

Downstream2B_Before.Threshold6<- Downstream2B_AllDO[which(Downstream2B_AllDO$TimeStamp=='Before' & Downstream2B_AllDO$Dissolved.Oxygen <= 6),]
Downstream2B_After.Threshold6<- Downstream2B_AllDO[which(Downstream2B_AllDO$TimeStamp=='After' & Downstream2B_AllDO$Dissolved.Oxygen <= 6),]
#Before:2019
#After: 8529

```



##Performing Threshold table before and after removal using DAILY MINIMUM of DO

```{r Take Daily Min of the X_AllDO datasets}
colnames(Upstream1_AllDO)[4] <- "DO"
colnames(Upstream2_AllDO)[4]<-"DO"
colnames(Impoundment1_AllDO)[4] <- "DO"
colnames(Downstream1_AllDO)[4]<-"DO"
colnames(Downstream2A_AllDO)[4]<-"DO"
colnames(Downstream2B_AllDO)[4]<-"DO"

#omit NA's in column of DO
Upstream1_AllDO<-Upstream1_AllDO[!(is.na(Upstream1_AllDO$DO)),]
#Take daily min
Upstream1_MinDO<-  
  Upstream1_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(DO))
#Total Min DO= 875

Upstream2_AllDO <- Upstream2_AllDO[!(is.na(Upstream2_AllDO$DO)),]
Upstream2_MinDO<-  
  Upstream2_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(DO))
#Total Min DO= 896

Impoundment1_AllDO <- Impoundment1_AllDO[!(is.na(Impoundment1_AllDO$DO)),]
Impoundment1_MinDO<-  
  Impoundment1_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(DO))
#Total Min DO= 805

Downstream1_AllDO <- Downstream1_AllDO[!(is.na(Downstream1_AllDO$DO)),]
Downstream1_MinDO<-  
  Downstream1_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(DO))
#Total Min DO= 763

Downstream2A_AllDO<- Downstream2A_AllDO[!(is.na(Downstream2A_AllDO$DO)),]
Downstream2A_MinDO<-  
  Downstream2A_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(DO))
#Total Min DO= 702

Downstream2B_AllDO<- Downstream2B_AllDO[!(is.na(Downstream2B_AllDO$DO)),]
Downstream2B_MinDO<-  
  Downstream2B_AllDO %>%
  group_by(Date) %>%
  summarise(MinDO = min(DO))
#Total Min DO= 902

```

```{r Divide each data set into before and after}
#Need to set timestamps now on MinDO datasets
class(Upstream1_MinDO$Date) #not a date, need to format as date
Upstream1_MinDO$Date <- as.Date(Upstream1_MinDO$Date, format = "%Y-%m-%d") #Now it is a date

Upstream1_MinDO_Before <- Upstream1_MinDO %>% filter(Date < as.Date("2017-09-21"))
#484
Upstream1_MinDO_After <- Upstream1_MinDO %>% filter(Date > as.Date("2017-09-21"))
#391

#Giving a timestamp- probably don't actually need to do this
Upstream1_MinDO_Before$TimeStamp<-"Before"
Upstream1_MinDO_After$TimeStamp<-"After"


#Upstream2
class(Upstream2_MinDO$Date) #not a date, need to format as date
Upstream2_MinDO$Date <- as.Date(Upstream2_MinDO$Date, format = "%Y-%m-%d") #Now it is a date

Upstream2_MinDO_Before <- Upstream2_MinDO %>% filter(Date < as.Date("2017-09-21"))
#505
Upstream2_MinDO_After <- Upstream2_MinDO %>% filter(Date > as.Date("2017-09-21"))
#391



#Impoundment1
class(Impoundment1_MinDO$Date) #not a date, need to format as date
Impoundment1_MinDO$Date <- as.Date(Impoundment1_MinDO$Date, format = "%Y-%m-%d") #Now it is a date

Impoundment1_MinDO_Before <- Impoundment1_MinDO %>% filter(Date < as.Date("2017-09-21"))
#421
Impoundment1_MinDO_After <- Impoundment1_MinDO %>% filter(Date > as.Date("2017-09-21"))
#384



#Downstream1
class(Downstream1_MinDO$Date) #not a date, need to format as date
Downstream1_MinDO$Date <- as.Date(Downstream1_MinDO$Date, format = "%Y-%m-%d") #Now it is a date

Downstream1_MinDO_Before <- Downstream1_MinDO %>% filter(Date < as.Date("2017-09-21"))
#496
Downstream1_MinDO_After <- Downstream1_MinDO %>% filter(Date > as.Date("2017-09-21"))
#267



#Downstream2A
class(Downstream2A_MinDO$Date) #not a date, need to format as date
Downstream2A_MinDO$Date <- as.Date(Downstream2A_MinDO$Date, format = "%Y-%m-%d") #Now it is a date

Downstream2A_MinDO_Before <- Downstream2A_MinDO %>% filter(Date < as.Date("2017-09-21"))
#343
Downstream2A_MinDO_After <- Downstream2A_MinDO %>% filter(Date > as.Date("2017-09-21"))
#359


#Downstream2B
class(Downstream2B_MinDO$Date) #not a date, need to format as date
Downstream2B_MinDO$Date <- as.Date(Downstream2B_MinDO$Date, format = "%Y-%m-%d") #Now it is a date

Downstream2B_MinDO_Before <- Downstream2B_MinDO %>% filter(Date < as.Date("2017-09-21"))
#529
Downstream2B_MinDO_After <- Downstream2B_MinDO %>% filter(Date > as.Date("2017-09-21"))
#373
```

```{r Test the thresholds}

Upstream1_MinDO_Before.Threshold4<- Upstream1_MinDO_Before[which(Upstream1_MinDO_Before$MinDO <= 4),]
#7
Upstream1_MinDO_After.Threshold4<- Upstream1_MinDO_After[which(Upstream1_MinDO_After$MinDO <= 4),]
#66

Upstream1_MinDO_Before.Threshold6<- Upstream1_MinDO_Before[which(Upstream1_MinDO_Before$MinDO <= 6),]
#82
Upstream1_MinDO_After.Threshold6<- Upstream1_MinDO_After[which(Upstream1_MinDO_After$MinDO <= 6),]
#114



#Upstream2
Upstream2_MinDO_Before.Threshold4<- Upstream2_MinDO_Before[which(Upstream2_MinDO_Before$MinDO <= 4),]
#9
Upstream2_MinDO_After.Threshold4<- Upstream2_MinDO_After[which(Upstream2_MinDO_After$MinDO <= 4),]
#16

Upstream2_MinDO_Before.Threshold6<- Upstream2_MinDO_Before[which(Upstream2_MinDO_Before$MinDO <= 6),]
#59
Upstream2_MinDO_After.Threshold6<- Upstream2_MinDO_After[which(Upstream2_MinDO_After$MinDO <= 6),]
#113



#Impoundment1
Impoundment1_MinDO_Before.Threshold4<- Impoundment1_MinDO_Before[which(Impoundment1_MinDO_Before$MinDO <= 4),]
#49
Impoundment1_MinDO_After.Threshold4<- Impoundment1_MinDO_After[which(Impoundment1_MinDO_After$MinDO <= 4),]
#51

Impoundment1_MinDO_Before.Threshold6<- Impoundment1_MinDO_Before[which(Impoundment1_MinDO_Before$MinDO <= 6),]
#132
Impoundment1_MinDO_After.Threshold6<- Impoundment1_MinDO_After[which(Impoundment1_MinDO_After$MinDO <= 6),]
#133




#Downstream1
Downstream1_MinDO_Before.Threshold4<- Downstream1_MinDO_Before[which(Downstream1_MinDO_Before$MinDO <= 4),]
#26
Downstream1_MinDO_After.Threshold4<- Downstream1_MinDO_After[which(Downstream1_MinDO_After$MinDO <= 4),]
#35

Downstream1_MinDO_Before.Threshold6<- Downstream1_MinDO_Before[which(Downstream1_MinDO_Before$MinDO <= 6),]
#41
Downstream1_MinDO_After.Threshold6<- Downstream1_MinDO_After[which(Downstream1_MinDO_After$MinDO <= 6),]
#64



#Downstream2A
Downstream2A_MinDO_Before.Threshold4<- Downstream2A_MinDO_Before[which(Downstream2A_MinDO_Before$MinDO <= 4),]
#0
Downstream2A_MinDO_After.Threshold4<- Downstream2A_MinDO_After[which(Downstream2A_MinDO_After$MinDO <= 4),]
#66

Downstream2A_MinDO_Before.Threshold6<- Downstream2A_MinDO_Before[which(Downstream2A_MinDO_Before$MinDO <= 6),]
#35
Downstream2A_MinDO_After.Threshold6<- Downstream2A_MinDO_After[which(Downstream2A_MinDO_After$MinDO <= 6),]
#160



#Downstream2B
Downstream2B_MinDO_Before.Threshold4<- Downstream2B_MinDO_Before[which(Downstream2B_MinDO_Before$MinDO <= 4),]
#6
Downstream2B_MinDO_After.Threshold4<- Downstream2B_MinDO_After[which(Downstream2B_MinDO_After$MinDO <= 4),]
#69

Downstream2B_MinDO_Before.Threshold6<- Downstream2B_MinDO_Before[which(Downstream2B_MinDO_Before$MinDO <= 6),]
#65
Downstream2B_MinDO_After.Threshold6<- Downstream2B_MinDO_After[which(Downstream2B_MinDO_After$MinDO <= 6),]
#157
```

