---
title: "Q1_AllDOValues"
author: "Kathleen Mason"
date: "1/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(ggridges)
library(dplyr)

getwd()

mytheme <- theme_light(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

Up1_processed<-read_csv("./Processed/Up1_processed.csv")
Up2_processed<-read_csv("./Processed/Up2_processed.csv")
Imp1_processed<-read_csv("./Processed/Imp1_processed.csv")
Imp2_processed<-read_csv("./Processed/Imp2_processed.csv")
Down1_processed<-read_csv("./Processed/Down1_processed.csv")
Down2A_processed<-read_csv("./Processed/Down2A_processed.csv")
Down2B_processed<-read_csv("./Processed/Down2B_processed.csv")

class(Up1_processed$Date)

colnames(Up1_processed)[4] <- "Dissolved Oxygen"
summary(Up1_processed$`Dissolved Oxygen`)
colnames(Imp1_processed)[5] <- "Dissolved Oxygen"
summary(Imp1_processed$`Dissolved Oxygen`)

colnames(Up2_processed)[4]<-"Dissolved Oxygen"
colnames(Imp2_processed)[6]<-"Dissolved Oxygen"

colnames(Down1_processed)[6]<-"Dissolved Oxygen"
colnames(Down2A_processed)[4]<-"Dissolved Oxygen"
colnames(Down2B_processed)[4]<-"Dissolved Oxygen"

#I need to select only date, time, site location and DO, then eliminate outliers- so set range of DO from 0-15, and set a before and after dam removal time stamp...then save these data sets to be used again.

#selecting date, time, site location, and DO

Upstream1_AllValues <- select(Up1_processed, 1:4)
Upstream2_AllValues <- select(Up2_processed, 1:4)
Impoundment1_AllValues <- select(Imp1_processed, 1:3, 5)
Downstream1_AllValues <- select(Down1_processed, 1:3, 6)
Downstream2A_AllValues <- select(Down2A_processed, 1:4)
Downstream2B_AllValues <- select(Down2B_processed, 1:4)



```

```{r Setting before and after timestamp and setting range 0-15}

Upstream1_AllValues_Before <- Upstream1_AllValues %>% filter(Date < as.Date("2017-09-21"))
Upstream1_AllValues_After <- Upstream1_AllValues %>% filter(Date > as.Date("2017-09-21"))
Upstream1_AllValues_After$TimeStamp<-"After"
Upstream1_AllValues_Before$TimeStamp<-"Before"
Upstream1_AllValues_TimeStamp<- full_join(Upstream1_AllValues_After, Upstream1_AllValues_Before)


Upstream2_AllValues_Before <- Upstream2_AllValues %>% filter(Date < as.Date("2017-09-21"))
Upstream2_AllValues_After <- Upstream2_AllValues %>% filter(Date > as.Date("2017-09-21"))
Upstream2_AllValues_After$TimeStamp<-"After"
Upstream2_AllValues_Before$TimeStamp<-"Before"
Upstream2_AllValues_TimeStamp<- full_join(Upstream2_AllValues_After, Upstream2_AllValues_Before)

class(Impoundment1_AllDO$Date)
Impoundment1_AllValues_Before <- Impoundment1_AllValues %>% filter(Date < as.Date("2017-09-21"))
Impoundment1_AllValues_After <- Impoundment1_AllValues %>% filter(Date > as.Date("2017-09-21"))
Impoundment1_AllValues_After$TimeStamp<-"After"
Impoundment1_AllValues_Before$TimeStamp<-"Before"
Impoundment1_AllValues_TimeStamp<- full_join(Impoundment1_AllValues_After, Impoundment1_AllValues_Before)

Downstream1_AllValues_Before <- Downstream1_AllValues %>% filter(Date < as.Date("2017-09-21"))
Downstream1_AllValues_After <- Downstream1_AllValues %>% filter(Date > as.Date("2017-09-21"))
Downstream1_AllValues_After$TimeStamp<-"After"
Downstream1_AllValues_Before$TimeStamp<-"Before"
Downstream1_AllValues_TimeStamp<- full_join(Downstream1_AllValues_After, Downstream1_AllValues_Before)

Downstream2A_AllValues_Before <- Downstream2A_AllValues %>% filter(Date < as.Date("2017-09-21"))
Downstream2A_AllValues_After <- Downstream2A_AllValues %>% filter(Date > as.Date("2017-09-21"))
Downstream2A_AllValues_After$TimeStamp<-"After"
Downstream2A_AllValues_Before$TimeStamp<-"Before"
Downstream2A_AllValues_TimeStamp<- full_join(Downstream2A_AllValues_After, Downstream2A_AllValues_Before)

Downstream2B_AllValues_Before <- Downstream2B_AllValues %>% filter(Date < as.Date("2017-09-21"))
Downstream2B_AllValues_After <- Downstream2B_AllValues %>% filter(Date > as.Date("2017-09-21"))
Downstream2B_AllValues_After$TimeStamp<-"After"
Downstream2B_AllValues_Before$TimeStamp<-"Before"
Downstream2B_AllValues_TimeStamp<- full_join(Downstream2B_AllValues_After, Downstream2B_AllValues_Before)


#Select range of data
#subset(df, date>4 & date<6)
#df[df$date>4 & df$date<6, ]
Upstream1_AllDO <- Upstream1_AllValues_TimeStamp[Upstream1_AllValues_TimeStamp$`Dissolved Oxygen`>= 0 & Upstream1_AllValues_TimeStamp$`Dissolved Oxygen`<= 15 , ]
summary(Upstream1_AllDO$`Dissolved Oxygen`)

Upstream2_AllDO <- Upstream2_AllValues_TimeStamp[Upstream2_AllValues_TimeStamp$`Dissolved Oxygen`>= 0 & Upstream2_AllValues_TimeStamp$`Dissolved Oxygen`<= 15 , ]

Impoundment1_AllDO <- Impoundment1_AllValues_TimeStamp[Impoundment1_AllValues_TimeStamp$`Dissolved Oxygen`>= 0 & Impoundment1_AllValues_TimeStamp$`Dissolved Oxygen`<= 15 , ]

Downstream1_AllDO <- Downstream1_AllValues_TimeStamp[Downstream1_AllValues_TimeStamp$`Dissolved Oxygen`>= 0 & Downstream1_AllValues_TimeStamp$`Dissolved Oxygen`<= 15 , ]

Downstream2A_AllDO <- Downstream2A_AllValues_TimeStamp[Downstream2A_AllValues_TimeStamp$`Dissolved Oxygen`>= 0 & Downstream2A_AllValues_TimeStamp$`Dissolved Oxygen`<= 15 , ]

Downstream2B_AllDO <- Downstream2B_AllValues_TimeStamp[Downstream2B_AllValues_TimeStamp$`Dissolved Oxygen`>= 0 & Downstream2B_AllValues_TimeStamp$`Dissolved Oxygen`<= 15 , ]
summary(Downstream2B_AllDO$`Dissolved Oxygen`)

write.csv(Upstream1_AllDO, row.names = FALSE, file =("./Processed/MilburnieDam_Upstream1_AllDO_processed.csv"))
write.csv(Upstream2_AllDO, row.names = FALSE, file =("./Processed/MilburnieDam_Upstream2_AllDO_processed.csv"))
write.csv(Impoundment1_AllDO, row.names = FALSE, file =("./Processed/MilburnieDam_Impoundment1_AllDO_processed.csv"))
write.csv(Downstream1_AllDO, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream1_AllDO_processed.csv"))
write.csv(Downstream2A_AllDO, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream2A_AllDO_processed.csv"))
write.csv(Downstream2B_AllDO, row.names = FALSE, file =("./Processed/MilburnieDam_Downstream2B_AllDO_processed.csv"))

```

```{r Q1 Re Using All Values- Upstream 1}

##Too many data points for a Shapiro test, way more than 5000
#Can we just skip normality test and assume it is not met??

#Wilcoxon Test
AllDO_Q1_Upstream1.twosample.wilcox <- wilcox.test(Upstream1_AllDO$`Dissolved Oxygen` ~ Upstream1_AllDO$TimeStamp) 

AllDO_Q1_Upstream1.twosample.wilcox
#Results
#W = 598854308, p-value < 2.2e-16
#alternative hypothesis: true location shift is not equal to 0

#Interpretation.... significant difference in Avg daily DO during and after the dam removal(p value<0.0001, Wilcoxon test, W=  598854308)

#Graph this!
MilburnieDam_AllDO_Q1_Upstream1_boxplot<-ggplot(Upstream1_AllDO) +
geom_boxplot(aes(x = Upstream1_AllDO$TimeStamp, y = Upstream1_AllDO$'Dissolved Oxygen'), color="skyblue4", alpha=0.75)+
  xlab("Timeframe in the Dam \nRemoval Process")+
  ylab("Dissolved \nOxygen (mgL)")+
  mytheme+
  ggtitle("Upstream Site 1")

MilburnieDam_AllDO_Q1_Upstream1_boxplot
  
ggsave("./Outputs/MilburnieDam_AllDO_Q1_Upstream1_boxplot.jpg", plot=MilburnieDam_AllDO_Q1_Upstream1_boxplot, width =10, height=6, units="in", dpi=300)

#summary stats
tapply(Upstream1_AllDO$'Dissolved Oxygen', Upstream1_AllDO$TimeStamp, summary)
#$After
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#0.000   6.217   7.667   7.405   9.930  13.467 

#$Before
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  0.000   6.967   9.583   9.421  11.667  14.580 

```

```{r Upstream 2}
##Too many data points for a Shapiro test, way more than 5000
#Can we just skip normality test and assume it is not met??

#Wilcoxon Test
AllDO_Q1_Upstream2.twosample.wilcox <- wilcox.test(Upstream2_AllDO$`Dissolved Oxygen` ~ Upstream2_AllDO$TimeStamp) 

AllDO_Q1_Upstream2.twosample.wilcox
#Results
#W = 669044063, p-value < 2.2e-16
#alternative hypothesis: true location shift is not equal to 0

#Interpretation.... significant difference in Avg daily DO during and after the dam removal(p value<0.0001, Wilcoxon test, W=  669044063)

#Graph this!
MilburnieDam_AllDO_Q1_Upstream2_boxplot<-ggplot(Upstream2_AllDO) +
geom_boxplot(aes(x = Upstream2_AllDO$TimeStamp, y = Upstream2_AllDO$'Dissolved Oxygen'), color="skyblue4", alpha=0.75)+
  xlab("Timeframe in the Dam \nRemoval Process")+
  ylab("Dissolved \nOxygen (mgL)")+
  mytheme+
  ggtitle("Upstream Site 2")

MilburnieDam_AllDO_Q1_Upstream2_boxplot
  
ggsave("./Outputs/MilburnieDam_AllDO_Q1_Upstream2_boxplot.jpg", plot=MilburnieDam_AllDO_Q1_Upstream2_boxplot, width =10, height=6, units="in", dpi=300)

#summary stats
tapply(Upstream2_AllDO$'Dissolved Oxygen', Upstream2_AllDO$TimeStamp, summary)
#$After
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#0.700   6.283   7.843   8.153  10.040  13.557 

#$Before
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  0.000   6.993   8.953   9.276  11.470  14.567 
```

```{r Impoundment}
##Too many data points for a Shapiro test, way more than 5000
#Can we just skip normality test and assume it is not met??

#Wilcoxon Test
AllDO_Q1_Impoundment1.twosample.wilcox <- wilcox.test(Impoundment1_AllDO$`Dissolved Oxygen` ~ Impoundment1_AllDO$TimeStamp) 

AllDO_Q1_Impoundment1.twosample.wilcox
#Results
#W = 605923100, p-value < 2.2e-16
#alternative hypothesis: true location shift is not equal to 0

#Interpretation.... significant difference in Avg daily DO during and after the dam removal(p value<0.0001, Wilcoxon test, W=  605923100)

#Graph this!
MilburnieDam_AllDO_Q1_Impoundment1_boxplot<-ggplot(Impoundment1_AllDO) +
geom_boxplot(aes(x = Impoundment1_AllDO$TimeStamp, y = Impoundment1_AllDO$'Dissolved Oxygen'), color="skyblue4", alpha=0.75)+
  xlab("Timeframe in the Dam \nRemoval Process")+
  ylab("Dissolved \nOxygen (mgL)")+
  mytheme+
  ggtitle("Impoundment Site 1")

MilburnieDam_AllDO_Q1_Impoundment1_boxplot
  
ggsave("./Outputs/MilburnieDam_AllDO_Q1_Impoundment1_boxplot.jpg", plot=MilburnieDam_AllDO_Q1_Impoundment1_boxplot, width =10, height=6, units="in", dpi=300)

#summary stats
tapply(Impoundment1_AllDO$'Dissolved Oxygen', Impoundment1_AllDO$TimeStamp, summary)
#$After
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 0.010   6.180   7.297   7.694   9.987  13.510 

#$Before
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    0.000   6.390   8.303   8.494  11.097  14.593 
```

```{r Downstream 1}
##Too many data points for a Shapiro test, way more than 5000
#Can we just skip normality test and assume it is not met??

#Wilcoxon Test
AllDO_Q1_Downstream1.twosample.wilcox <- wilcox.test(Downstream1_AllDO$`Dissolved Oxygen` ~ Downstream1_AllDO$TimeStamp) 

AllDO_Q1_Downstream1.twosample.wilcox
#Results
#W = 488055913, p-value < 2.2e-16
#alternative hypothesis: true location shift is not equal to 0

#Interpretation.... significant difference in Avg daily DO during and after the dam removal(p value<0.0001, Wilcoxon test, W=  488055913)

#Graph this!
MilburnieDam_AllDO_Q1_Downstream1_boxplot<-ggplot(Downstream1_AllDO) +
geom_boxplot(aes(x = Downstream1_AllDO$TimeStamp, y = Downstream1_AllDO$'Dissolved Oxygen'), color="skyblue4", alpha=0.75)+
  xlab("Timeframe in the Dam \nRemoval Process")+
  ylab("Dissolved \nOxygen (mgL)")+
  mytheme+
  ggtitle("Downstream Site 1")

MilburnieDam_AllDO_Q1_Downstream1_boxplot
  
ggsave("./Outputs/MilburnieDam_AllDO_Q1_Downstream1_boxplot.jpg", plot=MilburnieDam_AllDO_Q1_Downstream1_boxplot, width =10, height=6, units="in", dpi=300)

#summary stats
tapply(Downstream1_AllDO$'Dissolved Oxygen', Downstream1_AllDO$TimeStamp, summary)
#$After
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   0.000   6.960   9.060   8.476  10.423  13.260 

#$Before
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    0.000   7.603   9.300   9.402  11.470  14.320 
```

```{r Downstream 2A}
##Too many data points for a Shapiro test, way more than 5000
#Can we just skip normality test and assume it is not met??

#Wilcoxon Test
AllDO_Q1_Downstream2A.twosample.wilcox <- wilcox.test(Downstream2A_AllDO$`Dissolved Oxygen` ~ Downstream2A_AllDO$TimeStamp) 


AllDO_Q1_Downstream2A.twosample.wilcox
#Results
#W = 396568151, p-value < 2.2e-16
#alternative hypothesis: true location shift is not equal to 0

#Interpretation.... significant difference in Avg daily DO during and after the dam removal(p value<0.0001, Wilcoxon test, W=  396568151)

#Graph this!
MilburnieDam_AllDO_Q1_Downstream2A_boxplot<-ggplot(Downstream2A_AllDO) +
geom_boxplot(aes(x = Downstream2A_AllDO$TimeStamp, y = Downstream2A_AllDO$'Dissolved Oxygen'), color="skyblue4", alpha=0.75)+
  xlab("Timeframe in the Dam \nRemoval Process")+
  ylab("Dissolved \nOxygen (mgL)")+
  mytheme+
  ggtitle("Downstream Site 2A")

MilburnieDam_AllDO_Q1_Downstream2A_boxplot
  
ggsave("./Outputs/MilburnieDam_AllDO_Q1_Downstream2A_boxplot.jpg", plot=MilburnieDam_AllDO_Q1_Downstream2A_boxplot, width =10, height=6, units="in", dpi=300)

#summary stats
tapply(Downstream2A_AllDO$'Dissolved Oxygen', Downstream2A_AllDO$TimeStamp, summary)
#$After
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   0.000   5.646   7.460   7.714  10.050  14.247 

#$Before
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    4.307   7.037   8.433   8.960  11.027  14.310 
```

```{r Downstream 2B}
##Too many data points for a Shapiro test, way more than 5000
#Can we just skip normality test and assume it is not met??

#Wilcoxon Test
AllDO_Q1_Downstream2B.twosample.wilcox <- wilcox.test(Downstream2B_AllDO$`Dissolved Oxygen` ~ Downstream2B_AllDO$TimeStamp) 

AllDO_Q1_Downstream2B.twosample.wilcox
#Results
#W = 470690430, p-value < 2.2e-16
#alternative hypothesis: true location shift is not equal to 0

#Interpretation.... significant difference in Avg daily DO during and after the dam removal(p value<0.0001, Wilcoxon test, W=  470690430)

#Graph this!
MilburnieDam_AllDO_Q1_Downstream2B_boxplot<-ggplot(Downstream2B_AllDO) +
geom_boxplot(aes(x = Downstream2B_AllDO$TimeStamp, y = Downstream2B_AllDO$'Dissolved Oxygen'), color="skyblue4", alpha=0.75)+
  xlab("Timeframe in the Dam \nRemoval Process")+
  ylab("Dissolved \nOxygen (mgL)")+
  mytheme+
  ggtitle("Downstream Site 2B")

MilburnieDam_AllDO_Q1_Downstream2B_boxplot
  
ggsave("./Outputs/MilburnieDam_AllDO_Q1_Downstream2B_boxplot.jpg", plot=MilburnieDam_AllDO_Q1_Downstream2B_boxplot, width =10, height=6, units="in", dpi=300)

#summary stats
tapply(Downstream2B_AllDO$'Dissolved Oxygen', Downstream2B_AllDO$TimeStamp, summary)
#$After
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   0.000   5.997   7.093   7.317   9.183  13.630 

#$Before
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   0.4467  7.3133  9.5233  9.4048 11.3100 14.6333 
```

```{r All DO, site specific scatterplots}
colnames(Upstream1_AllDO)[4] <- "DO"
colnames(Upstream2_AllDO)[4]<-"DO"
colnames(Impoundment1_AllDO)[4] <- "DO"
colnames(Impoundment1_AllDO)[5] <- "TimeStamp"

colnames(Downstream1_AllDO)[4]<-"DO"
colnames(Downstream2A_AllDO)[4]<-"DO"
colnames(Downstream2B_AllDO)[4]<-"DO"


d=data.frame(date=as.Date(c("2017-09-21")), event=c("Dam Removal"))

Upstream1_AllDO_Scatterplot <-ggplot(Upstream1_AllDO, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") + ylim(0, 15) +ylab("Dissolved Oxygen (mg/L)")+ xlab("Sampling Date")+
scale_x_date(date_breaks = "1 year", date_minor_breaks= "months", date_labels = "%m/%y")+
  labs(title = "Upstream 1")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25))+   
    geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)
Upstream1_AllDO_Scatterplot
ggsave("./Outputs/MilburnieDam_Upstream1_AllDO_Scatterplot.jpg", plot=Upstream1_AllDO_Scatterplot, width =10, height=6, units="in", dpi=300)



Upstream2_AllDO_Scatterplot <-ggplot(Upstream2_AllDO, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") + ylim(0, 15) +ylab("Dissolved Oxygen (mg/L)")+ xlab("Sampling Date")+
scale_x_date(date_breaks = "1 year", date_minor_breaks= "months", date_labels = "%m/%y")+
  labs(title = "Upstream 2")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25))+   
    geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)
Upstream2_AllDO_Scatterplot
ggsave("./Outputs/MilburnieDam_Upstream2_AllDO_Scatterplot.jpg", plot=Upstream2_AllDO_Scatterplot, width =10, height=6, units="in", dpi=300)


Impoundment1_AllDO_Scatterplot <-ggplot(Impoundment1_AllDO, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") +
 ylim(0, 15) +
ylab("Dissolved Oxygen (mg/L)")+ xlab("Sampling Date")+
scale_x_date(date_breaks = "1 year", date_minor_breaks= "months", date_labels = "%m/%y")+
  labs(title = "Impoundment 1")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25))+   
    geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)
Impoundment1_AllDO_Scatterplot
ggsave("./Outputs/MilburnieDam_Impoundment1_AllDO_Scatterplot.jpg", plot=Impoundment1_AllDO_Scatterplot, width =10, height=6, units="in", dpi=300)

Downstream1_AllDO_Scatterplot <-ggplot(Downstream1_AllDO, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") +
 ylim(0, 15) +
ylab("Dissolved Oxygen (mg/L)")+ xlab("Sampling Date")+
scale_x_date(date_breaks = "1 year", date_minor_breaks= "months", date_labels = "%m/%y")+
  labs(title = "Downstream 1")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25))+   
    geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)
Downstream1_AllDO_Scatterplot
ggsave("./Outputs/MilburnieDam_Downstream1_AllDO_Scatterplot.jpg", plot=Downstream1_AllDO_Scatterplot, width =10, height=6, units="in", dpi=300)

Downstream2A_AllDO_Scatterplot <-ggplot(Downstream2A_AllDO, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") +
 ylim(0, 15) +
ylab("Dissolved Oxygen (mg/L)")+ xlab("Sampling Date")+
scale_x_date(date_breaks = "1 year", date_minor_breaks= "months", date_labels = "%m/%y")+
  labs(title = "Downstream 2A")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25))+   
    geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)
Downstream2A_AllDO_Scatterplot
ggsave("./Outputs/MilburnieDam_Downstream2A_AllDO_Scatterplot.jpg", plot=Downstream2A_AllDO_Scatterplot, width =10, height=6, units="in", dpi=300)


Downstream2B_AllDO_Scatterplot <-ggplot(Downstream2B_AllDO, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") +
 ylim(0, 15) +
ylab("Dissolved Oxygen (mg/L)")+ xlab("Sampling Date")+
scale_x_date(date_breaks = "1 year", date_minor_breaks= "months", date_labels = "%m/%y")+
  labs(title = "Downstream 2B")+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25))+   
    geom_vline(data=d, mapping=aes(xintercept=date), color="red", lty=5, size=.5)
Downstream2B_AllDO_Scatterplot
ggsave("./Outputs/MilburnieDam_Downstream2B_AllDO_Scatterplot.jpg", plot=Downstream2B_AllDO_Scatterplot, width =10, height=6, units="in", dpi=300)
```

```{r Put Multiple plots on 1 Page}
library("cowplot")

PLot_all<-plot_grid(Upstream2_AllDO_Scatterplot, Impoundment1_AllDO_Scatterplot, Downstream2B_AllDO_Scatterplot, 
         #labels = c("Upstream 2", "Impoundment 1", "Downstream 2B" ),
         ncol = 1, nrow = 3)
PLot_all
ggsave("./Outputs/MilburnieDam_AllDO_RepresentativeSites_Combined1.jpg", plot=PLot_all, width =10, height=6, units="in", dpi=300)
```

```{r}
#I want to make the graph above more beautiful
#SEparate each dataset into before and after- will then combine a total of 6 graphs nocol=2, nrow=3 this way there isn't a massive blank space
#Use these data sets that have already been made... Upstream1_AllValues_After and Upstream1_AllValues_Before
#Graph each of these for representative sites and then combine
colnames(Upstream2_AllValues_Before)[4]<-"DO"
colnames(Upstream2_AllValues_After)[4]<-"DO"
colnames(Impoundment1_AllValues_Before)[4]<-"DO"
colnames(Impoundment1_AllValues_After)[4]<-"DO"
colnames(Downstream2B_AllValues_Before)[4]<-"DO"
colnames(Downstream2B_AllValues_After)[4]<-"DO"


Upstream2_AllDO_Before <-ggplot(Upstream2_AllValues_Before, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") + ylim(0, 15)+
ylab("")+ xlab("")+
  labs(title = "Upstream 2 Before")+
  scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2013-10-11','2015-07-01')))+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12))
Upstream2_AllDO_Before

#Success!!!
#Now make this for after 
#then for before and after for the other two sites

Upstream2_AllDO_After <-ggplot(Upstream2_AllValues_After, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") + ylim(0, 15)+ylab("")+
 xlab("")+
  labs(title = "After")+
  scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2017-09-22','2019-07-10')))+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12))
Upstream2_AllDO_After



Impoundment1_AllDO_Before <-ggplot(Impoundment1_AllValues_Before, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") + ylim(0, 15)+
ylab("")+ xlab("")+
  labs(title = "Impoundment 1 Before")+
  scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2013-10-11','2015-07-01')))+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12))
Impoundment1_AllDO_Before

Impoundment1_AllDO_After <-ggplot(Impoundment1_AllValues_After, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") + ylim(0, 15)+ylab("")+
 xlab("")+
  labs(title = "After")+
  scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2017-09-22','2019-07-10')))+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12))
Impoundment1_AllDO_After


Downstream2B_AllDO_Before <-ggplot(Downstream2B_AllValues_Before, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") + ylim(0, 15)+
ylab("")+ xlab("")+
  labs(title = "Downstream 2B Before")+
  scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2013-10-11','2015-07-01')))+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12))
Downstream2B_AllDO_Before

Downstream2B_AllDO_After <-ggplot(Downstream2B_AllValues_After, aes(x = Date, y = DO)) +
geom_point(size=.25, color="royalblue4") + ylim(0, 15)+ ylab("")+
 xlab("")+
  labs(title = "After")+
  scale_x_date(date_breaks = "3 months", date_minor_breaks= "months", date_labels= "%m/%y", limits = as.Date(c('2017-09-22','2019-07-10')))+
  theme(panel.background = element_rect(fill = "grey97"),
        panel.grid.major = element_line(color = "gray68", size = 0.5),
        panel.grid.minor = element_line(color = "gray85", size = 0.25), plot.title = element_text(size = 10), axis.title.y = element_text(size = 12), axis.title.x = element_text(size = 12))
Downstream2B_AllDO_After


```

```{r Combine these}
library(grid)
library(gridExtra)

y.grob <- textGrob("DO (mg/L)", 
                   gp=gpar(fontsize=14), rot=90)
x.grob <- textGrob("Sampling Date", 
                   gp=gpar( fontsize=14))




AllDO_RepresentativeSites_CombinedPlot<-plot_grid(Upstream2_AllDO_Before,Upstream2_AllDO_After, Impoundment1_AllDO_Before, Impoundment1_AllDO_After, Downstream2B_AllDO_Before,Downstream2B_AllDO_After, 
         #labels = c("Upstream 2", "Impoundment 1", "Downstream 2B" ),
         ncol = 2, nrow = 3)


AllDO_RepresentativeSites_CombinedPlot2<-grid.arrange(arrangeGrob(AllDO_RepresentativeSites_CombinedPlot, left = y.grob, bottom=x.grob))

AllDO_RepresentativeSites_CombinedPlot2

ggsave("./Outputs/MilburnieDam_AAllDO_RepresentativeSites_CombinedPlot2.jpg", plot=AllDO_RepresentativeSites_CombinedPlot2, width =12, height=6, units="in", dpi=300)

```

```{r Boxplots of Rep Sites Before and After REmoval}
colnames(Upstream2_AllDO)[4]<-"DO"
Upstream2_AllDO_naomit <- Upstream2_AllDO[!(is.na(Upstream2_AllDO$DO)),]

#MilburnieDam_AllDO_Upstream2_boxplot<-ggplot(Upstream2_AllDO_naomit) +
#geom_boxplot(aes(x = TimeStamp, y = DO), color="skyblue4", alpha=0.75)+
 # xlab("Timeframe in the Dam \nRemoval Process")+
 # ylab("DO (mg/L)")+
#  mytheme+
#  ggtitle("Upstream Site 2")

MilburnieDam_AllDO_Upstream2_boxplot<-Upstream2_AllDO_naomit%>% ggplot(aes(x=reorder(TimeStamp,-DO, na.rm = TRUE), y=DO)) +
  geom_boxplot() +labs(y="", x="", subtitle = "Upstream 2")

MilburnieDam_AllDO_Upstream2_boxplot
ggsave("./Outputs/MilburnieDam_AllDO_Upstream2_boxplot.jpg", plot=MilburnieDam_AllDO_Upstream2_boxplot, width =10, height=6, units="in", dpi=300)

colnames(Impoundment1_AllDO)[4]<-"DO"
Impoundment1_AllDO_naomit <- Impoundment1_AllDO[!(is.na(Impoundment1_AllDO$DO)),]

MilburnieDam_AllDO_Impoundment1_boxplot<-Impoundment1_AllDO_naomit%>% ggplot(aes(x=reorder(TimeStamp,-DO, na.rm = TRUE), y=DO)) +
  geom_boxplot() +labs(y="", x="", 
       subtitle="Impoundment 1")

MilburnieDam_AllDO_Impoundment1_boxplot
ggsave("./Outputs/MilburnieDam_AllDO_Impoundment1_boxplot.jpg", plot=MilburnieDam_AllDO_Impoundment1_boxplot, width =10, height=6, units="in", dpi=300)



colnames(Downstream2B_AllDO)[4]<-"DO"
Downstream2B_AllDO_naomit <- Downstream2B_AllDO[!(is.na(Downstream2B_AllDO$DO)),]

MilburnieDam_AllDO_Downstream2B_boxplot<-Downstream2B_AllDO_naomit%>% ggplot(aes(x=reorder(TimeStamp,-DO, na.rm = TRUE), y=DO)) +
  geom_boxplot() +labs(y="", x="", 
       subtitle="Downstream 2B")

MilburnieDam_AllDO_Downstream2B_boxplot
ggsave("./Outputs/MilburnieDam_AllDO_Downstream2B_boxplot.jpg", plot=MilburnieDam_AllDO_Downstream2B_boxplot, width =10, height=6, units="in", dpi=300)




#Combine all three into one page now!


y.grob <- textGrob("DO (mg/L)", 
                   gp=gpar(fontsize=14), rot=90)

AllDO_RepresentativeSites_BeforeAfterBoxplots<-plot_grid(MilburnieDam_AllDO_Upstream2_boxplot, MilburnieDam_AllDO_Impoundment1_boxplot, MilburnieDam_AllDO_Downstream2B_boxplot,
         #labels = c("Upstream 2", "Impoundment 1", "Downstream 2B" ),
         ncol = 1, nrow = 3)
AllDO_RepresentativeSites_BeforeAfterBoxplots

AllDO_RepresentativeSites_BeforeAfterBoxplots2<-grid.arrange(arrangeGrob(AllDO_RepresentativeSites_BeforeAfterBoxplots, left = y.grob))

ggsave("./Outputs/AllDO_RepresentativeSites_BeforeAfterBoxplots2.jpg", plot=AllDO_RepresentativeSites_BeforeAfterBoxplots2, width =6, height=10, units="in", dpi=300)


```

```{r Downstream 2B}
##Too many data points for a Shapiro test, way more than 5000
#Can we just skip normality test and assume it is not met??

#Wilcoxon Test
AllDO_Q1_Downstream2B.twosample.wilcox <- wilcox.test(Downstream2B_AllDO$DO ~ Downstream2B_AllDO$TimeStamp) 

AllDO_Q1_Downstream2B.twosample.wilcox
#Results
#W = 470690430, p-value < 2.2e-16
#alternative hypothesis: true location shift is not equal to 0

#Interpretation.... significant difference in Avg daily DO during and after the dam removal(p value<0.0001, Wilcoxon test, W=  470690430)

#Graph this!
MilburnieDam_AllDO_Q1_Downstream2B_boxplot<-ggplot(Downstream2B_AllDO) +
geom_boxplot(aes(x = Downstream2B_AllDO$TimeStamp, y = Downstream2B_AllDO$DO), color="skyblue4", alpha=0.75)+
  xlab("Timeframe in the Dam \nRemoval Process")+
  ylab("Dissolved \nOxygen (mgL)")+
  mytheme+
  ggtitle("Downstream Site 2B")

MilburnieDam_AllDO_Q1_Downstream2B_boxplot
  
ggsave("./Outputs/MilburnieDam_AllDO_Q1_Downstream2B_boxplot.jpg", plot=MilburnieDam_AllDO_Q1_Downstream2B_boxplot, width =10, height=6, units="in", dpi=300)

#summary stats
tapply(Downstream2B_AllDO$DO, Downstream2B_AllDO$TimeStamp, summary)
#$After
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   0.000   5.997   7.093   7.317   9.183  13.630 

#$Before
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   0.4467  7.3133  9.5233  9.4048 11.3100 14.6333 
```
